#! /bin/sh
# Initialize some variables.
prefix=/usr/local
exec_prefix=/usr/local
bindir=${exec_prefix}/bin
sysconfdir="${prefix}/etc"
PACKAGE_NAME=holy
PACKAGE_VERSION=2.02
datarootdir="/usr/local/share"
datadir="${datarootdir}"
if [ "x$pkgdatadir" = x ]; then
    pkgdatadir="${datadir}/holy"
fi

self=`basename $0`

holy_editenv=${bindir}/holy-editenv
rootdir=
bootdir=
holydir=`echo "/boot/holy" | sed 's,//*,/,g'`

export TEXTDOMAIN=holy
export TEXTDOMAINDIR="${datarootdir}/locale"

. "${pkgdatadir}/holy-mkconfig_lib"

# Usage: usage
# Print the usage.
usage () {
    gettext_printf "Usage: %s [OPTION] MENU_ENTRY\n" "$self"
    gettext "Set the default boot menu entry for holy, for the next boot only."; echo
    print_option_help "-h, --help" "$(gettext "print this message and exit")"
    print_option_help "-V, --version" "$(gettext "print the version information and exit")"
    dirmsg="$(gettext_printf "expect holy images under the directory DIR/%s instead of the %s directory" "holy" "$holydir")"
    print_option_help "--boot-directory=$(gettext "DIR")" "$dirmsg"
    echo
    gettext "MENU_ENTRY is a number, a menu item title or a menu item identifier. Please note that menu items in
submenus or sub-submenus require specifying the submenu components and then the
menu item component. The titles should be separated using the greater-than
character (>) with no extra spaces. Depending on your shell some characters including > may need escaping. More information about this is available
in the holy Manual in the section about the 'default' command. "; echo
    echo
    gettext "Report bugs to <bashscripter123@gmail.com>."; echo
}

argument () {
  opt=$1
  shift

  if test $# -eq 0; then
      gettext_printf "%s: option requires an argument -- \`%s'\n" "$self" "$opt" 1>&2
      exit 1
  fi
  echo $1
}

# Check the arguments.
while test $# -gt 0
do
    option=$1
    shift

    case "$option" in
    -h | --help)
	usage
	exit 0 ;;
    -V | --version)
	echo "$self (${PACKAGE_NAME}) ${PACKAGE_VERSION}"
	exit 0 ;;

# Accept for compatibility
    --root-directory)
	rootdir=`argument $option "$@"`; shift ;;
    --root-directory=*)
	rootdir=`echo "$option" | sed 's/--root-directory=//'` ;;

    --boot-directory)
    bootdir=`argument $option "$@"`; shift;;
    --boot-directory=*)
    bootdir=`echo "$option" | sed 's/--boot-directory=//'` ;;

    -*)
	gettext_printf "Unrecognized option \`%s'\n" "$option" 1>&2
	usage
	exit 1
	;;
    *)
	if test "x$entry" != x; then
	    gettext "More than one menu entry?" 1>&2
	    echo >&2
	    usage
	    exit 1
	fi
	entry="${option}" ;;
    esac
done

if test "x$entry" = x; then
    gettext "Menu entry not specified." 1>&2
    echo >&2
    usage
    exit 1
fi

if [ -z "$bootdir" ]; then
    # Default bootdir if bootdir not initialized.
    bootdir=/boot

    if [ -n "$rootdir" ] ; then
        # Initialize bootdir if rootdir was initialized.
        bootdir=${rootdir}/boot
    fi
fi

holydir=`echo "${bootdir}/holy" | sed 's,//*,/,g'`

# Restore saved_entry if it was set by previous version
prev_saved_entry=`$holy_editenv ${holydir}/holyenv list | sed -n 's/^prev_saved_entry=//p'`
if [ "$prev_saved_entry" ]; then
    $holy_editenv ${holydir}/holyenv set saved_entry="$prev_saved_entry"
    $holy_editenv ${holydir}/holyenv unset prev_saved_entry
fi

$holy_editenv ${holydir}/holyenv set next_entry="$entry"

# Bye.
exit 0
