#!/bin/sh
# Copyright 2025 Felix P. A. Gillberg HolyBooter
# SPDX-License-Identifier: GPL-2.0


rsync -Lrtvz translationproject.org::tp/latest/holy/ po

autogenerated="en@quot en@hebrew de@hebrew en@cyrillic en@greek en@arabic en@piglatin de_CH"


for x in $autogenerated; do
    rm -f "po/$x.po";
done


(
    (
	cd po && ls *.po| cut -d. -f1
	for x in $autogenerated; do
	    echo "$x";
	done
    ) | sort | uniq | xargs
) >po/LINGUAS
