/*
 * Copyright 2025 Felix P. A. Gillberg HolyBooter
 * SPDX-License-Identifier: GPL-2.0
 */

#ifndef holy_LOONGSON_CPU_HEADER
#define holy_LOONGSON_CPU_HEADER	1

#include <holy/cpu/mips.h>

#define holy_CPU_LOONGSON_FLASH_START            0xbfc00000
#define holy_CPU_LOONGSON_FLASH_TLB_REFILL       0xbfc00200
#define holy_CPU_LOONGSON_FLASH_CACHE_ERROR      0xbfc00300
#define holy_CPU_LOONGSON_FLASH_OTHER_EXCEPTION  0xbfc00380

#define holy_CPU_LOONGSON_DDR2_BASE              0xaffffe00
#define holy_CPU_LOONGSON_DDR2_REG1_HI_8BANKS    0x00000001
#define holy_CPU_LOONGSON_DDR2_REG_SIZE          0x8
#define holy_CPU_LOONGSON_DDR2_REG_STEP          0x10

#define holy_CPU_LOONGSON_COP0_CACHE_CONFIG holy_CPU_REGISTER_WRAP($16)
#define holy_CPU_LOONGSON_COP0_CACHE_CONFIG_ILINESIZE 0x10
#define holy_CPU_LOONGSON_COP0_CACHE_CONFIG_DLINESIZE 0x8
#define holy_CPU_LOONGSON_COP0_CACHE_DSIZE_SHIFT 6
#define holy_CPU_LOONGSON_COP0_CACHE_ISIZE_SHIFT 9
#define holy_CPU_LOONGSON_COP0_CACHE_SIZE_MASK  0x7
#define holy_CPU_LOONGSON_COP0_CACHE_SIZE_OFFSET 12

#define holy_CPU_LOONGSON_COP0_I_INDEX_INVALIDATE 0
#define holy_CPU_LOONGSON_COP0_D_INDEX_TAG_STORE  9
#define holy_CPU_LOONGSON_COP0_S_INDEX_TAG_STORE  11

#define holy_CPU_LOONGSON_COP0_I_INDEX_BIT_OFFSET 5
#define holy_CPU_LOONGSON_COP0_D_INDEX_BIT_OFFSET 5
#define holy_CPU_LOONGSON_COP0_S_INDEX_BIT_OFFSET 5

#define holy_CPU_LOONGSON_CACHE_ACCELERATED 7
#define holy_CPU_LOONGSON_CACHE_UNCACHED 2
#define holy_CPU_LOONGSON_CACHE_CACHED 3
#define holy_CPU_LOONGSON_CACHE_TYPE_MASK 7
#define holy_CPU_LOONGSON_CACHE_LINE_SIZE_LOG_SMALL 4
#define holy_CPU_LOONGSON_CACHE_LINE_SIZE_LOG_BIG 5
#define holy_CPU_LOONGSON_CACHE_LINE_SIZE_SMALL 16
#define holy_CPU_LOONGSON_CACHE_LINE_SIZE_BIG 32

#define holy_CPU_LOONGSON_I_CACHE_LOG_WAYS 2
#define holy_CPU_LOONGSON_D_CACHE_LOG_WAYS 2
#define holy_CPU_LOONGSON_S_CACHE_LOG_WAYS 2

/* FIXME: determine dynamically.  */
#define holy_CPU_LOONGSON_SECONDARY_CACHE_LOG_SIZE 19

#define holy_CPU_LOONGSON_COP0_BADVADDR holy_CPU_REGISTER_WRAP($8)
#define holy_CPU_LOONGSON_COP0_CAUSE holy_CPU_REGISTER_WRAP($13)
#define holy_CPU_LOONGSON_COP0_EPC holy_CPU_REGISTER_WRAP($14)
#define holy_CPU_LOONGSON_COP0_PRID holy_CPU_REGISTER_WRAP($15)
#define holy_CPU_LOONGSON_COP0_CACHE_TAGLO holy_CPU_REGISTER_WRAP($28)
#define holy_CPU_LOONGSON_COP0_CACHE_TAGHI holy_CPU_REGISTER_WRAP($29)

#define holy_CPU_LOONGSON_LIOCFG   0xbfe00108
#define holy_CPU_LOONGSON_ROM_DELAY_OFFSET 2
#define holy_CPU_LOONGSON_ROM_DELAY_MASK 0x1f
#define holy_CPU_LOONGSON_CORECFG   0xbfe00180
#define holy_CPU_LOONGSON_CORECFG_DISABLE_DDR2_SPACE 0x100
#define holy_CPU_LOONGSON_CORECFG_BUFFER_CPU 0x200

#define holy_CPU_LOONGSON_PCI_HIT1_SEL_LO   0xbfe00150
#define holy_CPU_LOONGSON_PCI_HIT1_SEL_HI   0xbfe00154

#define holy_CPU_LOONGSON_GPIOCFG  0xbfe00120
#define holy_CPU_YEELOONG_SHUTDOWN_GPIO 1

#endif
