#! /bin/sh
#

nm="$1"
shift

cat <<EOF
/*
* THIS FILE IS AUTOGENERATED. DO NOT TOUCH !
* Copyright (C) holybooter 2025
*
*
*/
EOF

cat <<EOF
void holy_init_all (void);
void holy_fini_all (void);
EOF

read mods
for line in $mods; do
  if ${nm} --defined-only -P -p ${line} | grep holy_mod_init > /dev/null; then
      echo "void holy_${line%%.*}_init (void);"
  fi
  if ${nm} --defined-only -P -p ${line} | grep holy_mod_fini > /dev/null; then
      echo "void holy_${line%%.*}_fini (void);"
  fi
done
