/*
* AUTOGENERATED FILE ---- DO NOT TOUCH ------
*   Copyright (C) holybooter 2025
*
*
*
*/
#include <../config.h>
#include <../include/holy/cache.h>
#include <../include/holy/command.h>
#include <../include/holy/device.h>
#include <../include/holy/disk.h>
#include <../include/holy/dl.h>
#include <../include/holy/env.h>
#include <../include/holy/env_private.h>
#include <../include/holy/err.h>
#include <../include/holy/file.h>
#include <../include/holy/fs.h>
#include <../include/holy/i18n.h>
#include <../include/holy/kernel.h>
#include <../include/holy/list.h>
#include <../include/holy/misc.h>
#include <../include/holy/compiler-rt.h>
#include <../include/holy/mm.h>
#include <../include/holy/parser.h>
#include <../include/holy/partition.h>
#include <../include/holy/term.h>
#include <../include/holy/time.h>
#include <../include/holy/mm_private.h>
#include <../include/holy/net.h>
#include <../include/holy/tpm.h>
#include <../include/holy/memory.h>
#include <../include/holy/machine/kernel.h>
#include <../include/holy/machine/pxe.h>
#include <../include/holy/machine/int.h>
#include <../include/holy/i386/tsc.h>

#define COMPILE_TIME_ASSERT(cond) switch (0) { case 1: case !(cond): ; }

#pragma GCC diagnostic ignored "-Wmissing-format-attribute"

void
holy_register_exported_symbols (void)
{
  struct symtab { const char *name; void *addr; int isfunc; };
  struct symtab *p;
  static struct symtab tab[] =
    {
      {0, 0, 0}
    };

  COMPILE_TIME_ASSERT (sizeof (tab) > sizeof (tab[0]));
  for (p = tab; p->name; p++)
    holy_dl_register_symbol (p->name, p->addr, p->isfunc, 0);
}
